version: '3'
services:
  zookeeper:
    container_name: lnmp_zookeeper
    image: wurstmeister/zookeeper
    volumes:
      - ${ZOOKEEPER_DATA_DIR}:/etc/zookeeper:rw
    # mem_limit: 1024M
    environment:
      - ZOOKEEPER_CLIENT_PORT=${ZOOKEEPER_CLIENT_PORT}
      - ZOOKEEPER_TICK_TIME=${ZOOKEEPER_TICK_TIME}
    ports:
      - ${ZOOKEEPER_CLIENT_PORT}:2181
    restart: always

  kafka1:
    container_name: lnmp_kafka1
    image: wurstmeister/kafka
    # mem_limit: 1024M
    depends_on:
      - zookeeper
    ports:
      - 9092:9092
    environment:
      KAFKA_ADVERTISED_HOST_NAME: 10.44.4.17 #宿主机IP 10.44.4.17
      KAFKA_MESSAGE_MAX_BYTES: 2000000
      KAFKA_BROKER_ID: 1 #指定kafka的id
      KAFKA_ADVERTISED_PORT: 9092 #kafka外放端口
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
    volumes:
      - ${KAFKA_LOG_DIR}1:/kafka:rw
      - /etc/localtime:/etc/localtime
  
  kafka2:
    container_name: lnmp_kafka2
    image: wurstmeister/kafka
    # mem_limit: 1024M
    depends_on:
      - zookeeper
    ports:
      - 9093:9092
    environment:
      KAFKA_ADVERTISED_HOST_NAME: 10.44.4.17 #宿主机IP 10.44.4.17
      KAFKA_MESSAGE_MAX_BYTES: 2000000
      KAFKA_BROKER_ID: 2 #指定kafka的id
      KAFKA_ADVERTISED_PORT: 9093 #kafka外放端口
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
    volumes:
      - ${KAFKA_LOG_DIR}2:/kafka:rw
      - /etc/localtime:/etc/localtime

  kafka3:
    container_name: lnmp_kafka3
    image: wurstmeister/kafka
    # mem_limit: 1024M
    depends_on:
      - zookeeper
    ports:
      - 9094:9092
    environment:
      KAFKA_ADVERTISED_HOST_NAME: 10.44.4.17 #宿主机IP 10.44.4.17
      KAFKA_MESSAGE_MAX_BYTES: 2000000
      KAFKA_BROKER_ID: 3 #指定kafka的id
      KAFKA_ADVERTISED_PORT: 9094 #kafka外放端口
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
    volumes:
      - ${KAFKA_LOG_DIR}3:/kafka:rw
      - /etc/localtime:/etc/localtime

  kafka-manager:
    container_name: lnmp_kafka_manager
    image: sheepkiller/kafka-manager
    ports:
      - ${KAFKA_MANAGER_PORT}:9000
    environment:
      ZK_HOSTS: zookeeper:2181
    depends_on:
      - zookeeper
    restart: always
